### ISSUE TITLE
Spacecrafts Page Todo List

### ISSUE THREAD

**Issue by NAlexH2** [NAlexH2/frontend-stapi#5]
- [x] Generate species list w/ Postman
- [x] Generate spacecraft list
- [x] Cross reference each list to only build a static local collection of species to be searched from that eventually gets passed to the API call to pull up that species lists of spacecrafts
- [x] Implement a cool predictive searchbar
- [x] Make API call to starpi
- [x] Display response in a neat and cool way (see wireframe)
