### ISSUE TITLE
Performers View Todo List

### ISSUE THREAD

**Issue by NAlexH2** [NAlexH2/frontend-stapi#6]
- [ ] On page load, make API call to STAPI to collect how many actors were part of each series.
    - NOTE: DO NOT PULL ALL ACTORS FROM EACH SERIES, JUST THE TOTAL NUMBER!!!!
- [ ] Display a graph with total number of actors for that series
- [ ] Make graph intractable? If not possible, add buttons for each series to display performer list.
- [ ] When button or graph spot clicked, display a list of performers in alphabetical order below the graph in a neat and cool way.
    - NOTE: DO NOT MAKE THE PAGE SUPER LONG WITH THE LIST OF ACTORS!!!! Make a neat and cool scrollable box to display the actor info!
