### ISSUE TITLE
Run Dates Stats View Todo List

### ISSUE THREAD

**Issue by NAlexH2** [NAlexH2/frontend-stapi#7]
- [x] On page load, make call to STAPI to get all shows run dates (start and end) as well as when all movies theatrical release dates
- [x] Take data and load it into a neat and cool gantt timeline chart
- [x] Make sure series is either on the chart with the line, or on the **y-axis**, same with movies.
- [x] **x-axis** should have MM/YY
- [x] Freeze labels on the left side so people know what is what
- [x] Make gantt chart scrollable because it's gunna have a lot of YY/MM on the x-axis

**Comment by NAlexH2** [comment]
Closing for #9
